// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiAEmEXSAQhIcbvh5OAECn_iVx9W2WZB8',
    appId: '1:226795562214:web:9db6de93caab8809b9c727',
    messagingSenderId: '226795562214',
    projectId: 'sae-mobile-b1a53',
    authDomain: 'sae-mobile-b1a53.firebaseapp.com',
    storageBucket: 'sae-mobile-b1a53.appspot.com',
    measurementId: 'G-2FQ3GLY06K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jFwPcXEKwyUYpLshEFmVbVg_3Jfcai8',
    appId: '1:226795562214:android:15e1d68bcc10cb9eb9c727',
    messagingSenderId: '226795562214',
    projectId: 'sae-mobile-b1a53',
    storageBucket: 'sae-mobile-b1a53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByUFyFQAi01D6EikkHxnxaV_Jqm0bhHOo',
    appId: '1:226795562214:ios:8024edf5fbaddf6db9c727',
    messagingSenderId: '226795562214',
    projectId: 'sae-mobile-b1a53',
    storageBucket: 'sae-mobile-b1a53.appspot.com',
    iosClientId: '226795562214-6e1fge9vg1dkjcsi4fclthlsenldhikg.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByUFyFQAi01D6EikkHxnxaV_Jqm0bhHOo',
    appId: '1:226795562214:ios:8024edf5fbaddf6db9c727',
    messagingSenderId: '226795562214',
    projectId: 'sae-mobile-b1a53',
    storageBucket: 'sae-mobile-b1a53.appspot.com',
    iosClientId: '226795562214-6e1fge9vg1dkjcsi4fclthlsenldhikg.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );
}
